// ============================================================================
// AUTO-GENERATED by fb-gen — DO NOT EDIT
// ============================================================================
#ifndef FIREBOLT_ACTIONS_H
#define FIREBOLT_ACTIONS_H

#include <functional>
#include <optional>
#include <string>
#include <unordered_map>
#include <vector>
#include <firebolt/types.h>

namespace Firebolt::Actions {

class IActions {
public:
    virtual ~IActions() = default;

    virtual Result<void> start(const std::string& intent) const = 0;

    virtual Result<SubscriptionId> subscribeOnIntent(std::function<void(const std::string&)>&& notification) = 0;
    virtual Result<SubscriptionId> subscribeOnIntentChanged(std::function<void(const std::string&)>&& notification) {
        return subscribeOnIntent(std::move(notification));
    }

    virtual Result<void> unsubscribe(SubscriptionId id) = 0;
    virtual void unsubscribeAll() = 0;

};  // class IActions

} // namespace Firebolt::Actions

#endif // FIREBOLT_ACTIONS_H
