/**
 * Copyright 2026 Comcast Cable Communications Management, LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
//
// ============================================================================
// AUTO-GENERATED by firebolt-sdk-gen v0.1.0 — DO NOT EDIT
// ============================================================================
#ifndef FIREBOLT_VIDEOOUTPUT_H
#define FIREBOLT_VIDEOOUTPUT_H

#include <array>
#include <firebolt/types.h>
#include <functional>
#include <string>
#include <vector>

namespace Firebolt::VideoOutput
{
enum class CecStateValue
{
    Active,
    Inactive,
    Unsupported,
};

enum class ColorDepthValue
{
    D0,
    D10,
    D12,
    D8,
};

enum class ColorFormatValue
{
    None,
    Rgb444,
    Ycbcr420,
    Ycbcr422,
    Ycbcr444,
};

enum class DynamicRangeValue
{
    DolbyVision,
    Hdr10,
    Hdr10plus,
    Hlg,
    None,
    Sdr,
};

enum class HdcpState
{
    Direct,
    Hdcp14,
    Hdcp22,
    None,
};

enum class OutputColorimetry
{
    Bt2020rgb,
    Bt2020ycc,
    Bt709,
    None,
    Oprgb,
};

enum class QuantizationRangeValue
{
    Full,
    Limited,
    None,
};

enum class RefreshRateValue
{
    R0,
    R23976,
    R24,
    R25,
    R2997,
    R30,
    R50,
    R5994,
    R60,
};

struct VideoOutputResolution
{
    uint32_t height;
    uint32_t width;
};

class IVideoOutput
{
public:
    virtual ~IVideoOutput() = default;

    [[nodiscard]] virtual Result<CecStateValue> cecState() const = 0;
    virtual Result<SubscriptionId> subscribeOnCecStateChanged(std::function<void(const CecStateValue&)>&& notification) = 0;

    [[nodiscard]] virtual Result<ColorDepthValue> colorDepth() const = 0;

    [[nodiscard]] virtual Result<ColorFormatValue> colorFormat() const = 0;

    [[nodiscard]] virtual Result<OutputColorimetry> colorimetry() const = 0;

    [[nodiscard]] virtual Result<DynamicRangeValue> dynamicRange() const = 0;

    [[nodiscard]] virtual Result<HdcpState> hdcp() const = 0;
    virtual Result<SubscriptionId> subscribeOnHdcpChanged(std::function<void(const HdcpState&)>&& notification) = 0;

    [[nodiscard]] virtual Result<QuantizationRangeValue> quantizationRange() const = 0;

    [[nodiscard]] virtual Result<RefreshRateValue> refreshRate() const = 0;
    virtual Result<SubscriptionId>
    subscribeOnRefreshRateChanged(std::function<void(const RefreshRateValue&)>&& notification) = 0;

    [[nodiscard]] virtual Result<VideoOutputResolution> resolution() const = 0;
    virtual Result<SubscriptionId>
    subscribeOnResolutionChanged(std::function<void(const VideoOutputResolution&)>&& notification) = 0;

    virtual Result<void> unsubscribe(SubscriptionId id) = 0;
    virtual void unsubscribeAll() = 0;

}; // class IVideoOutput

#ifndef FIREBOLT_NO_METHOD_AVAILABILITY

/// Enum of available methods in this module for runtime capability queries.
enum class MethodId
{
    resolution = 0,
    hdcp = 1,
    cecState = 2,
    refreshRate = 3,
    colorDepth = 4,
    colorFormat = 5,
    colorimetry = 6,
    dynamicRange = 7,
    quantizationRange = 8,
};

/// Check if a method is available in this SDK build.
/// Returns true if the method is compiled in, false otherwise.
/// All methods in this build are currently available (true).
inline bool isMethodAvailable(MethodId method) noexcept
{
    static constexpr bool kMethodAvailable[] = {
        true, true, true, true, true, true, true, true, true,
    };
    const int idx = static_cast<int>(method);
    if (idx < 0 || idx >= static_cast<int>(sizeof(kMethodAvailable) / sizeof(kMethodAvailable[0])))
    {
        return false;
    }
    return kMethodAvailable[idx];
}

/// Static array containing all available methods in this module.
/// Use for convenient enumeration: for (auto m : allMethods) { ... }
static constexpr std::array<MethodId, 9> allMethods = {
    MethodId::resolution,  MethodId::hdcp,         MethodId::cecState,
    MethodId::refreshRate, MethodId::colorDepth,   MethodId::colorFormat,
    MethodId::colorimetry, MethodId::dynamicRange, MethodId::quantizationRange,
};

#endif // FIREBOLT_NO_METHOD_AVAILABILITY

} // namespace Firebolt::VideoOutput

#endif // FIREBOLT_VIDEOOUTPUT_H
