/**
 * Copyright 2026 Comcast Cable Communications Management, LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
//
// ============================================================================
// AUTO-GENERATED by fb-gen — DO NOT EDIT
// ============================================================================
#include "actions_impl.h"
#include "json_types/actions.h"
#include <firebolt/json_types.h>

namespace Firebolt::Actions
{

ActionsImpl::ActionsImpl(Firebolt::Helpers::IHelper& helper)
    : helper_(helper),
      subscriptionManager_(helper, this)
{
}

Result<Intent> ActionsImpl::intent() const
{
    return helper_.get<JsonData::JsonValue, Intent>("Actions.intent");
}

Result<SubscriptionId> ActionsImpl::subscribeOnIntent(std::function<void(const Intent&)>&& notification)
{
    return subscriptionManager_.subscribe<JsonData::JsonValue>("Actions.onIntent", std::move(notification));
}

Result<void> ActionsImpl::start(const std::string& intent, std::optional<std::string> handlerAppId) const
{
    nlohmann::json params;
    try
    {
        params["intent"] = nlohmann::json::parse(intent);
    }
    catch (const nlohmann::json::parse_error&)
    {
        return Firebolt::Result<void>{Firebolt::Error::InvalidParams};
    }
    if (handlerAppId)
    {
        params["handlerAppId"] = *handlerAppId;
    }
    return helper_.invoke("Actions.start", params);
}

Result<void> ActionsImpl::unsubscribe(SubscriptionId id)
{
    return subscriptionManager_.unsubscribe(id);
}

void ActionsImpl::unsubscribeAll()
{
    subscriptionManager_.unsubscribeAll();
}

} // namespace Firebolt::Actions
