/**
 * Copyright 2026 Comcast Cable Communications Management, LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
//
// ============================================================================
// AUTO-GENERATED by fb-gen — DO NOT EDIT
// ============================================================================
#ifndef FIREBOLT_ACTIONS_IMPL_H
#define FIREBOLT_ACTIONS_IMPL_H

#include "firebolt/actions.h"
#include <firebolt/helpers.h>

namespace Firebolt::Actions {

class ActionsImpl : public IActions {
public:
    explicit ActionsImpl(Firebolt::Helpers::IHelper& helper);
    ActionsImpl(const ActionsImpl&) = delete;
    ActionsImpl& operator=(const ActionsImpl&) = delete;
    ~ActionsImpl() override = default;

    Result<std::string> intent() const override;

    Result<SubscriptionId> subscribeOnIntent(std::function<void(const std::string&)>&& notification) override;

    Result<void> unsubscribe(SubscriptionId id) override;
    void unsubscribeAll() override;

private:
    Firebolt::Helpers::IHelper& helper_;
    Firebolt::Helpers::SubscriptionManager subscriptionManager_;
};

} // namespace Firebolt::Actions

#endif // FIREBOLT_ACTIONS_IMPL_H
