// ============================================================================
// AUTO-GENERATED by fb-gen — DO NOT EDIT
// ============================================================================
#include "actions_impl.h"
#include "json_types/actions.h"
#include <firebolt/json_types.h>
#include <nlohmann/json.hpp>

namespace Firebolt::Actions {

ActionsImpl::ActionsImpl(Firebolt::Helpers::IHelper& helper)
    : helper_(helper),
      subscriptionManager_(helper, this)
{}

Result<std::string> ActionsImpl::intent() const {
    return helper_.get<Firebolt::JSON::String, std::string>("actions.intent");
}

Result<SubscriptionId> ActionsImpl::subscribeOnIntent(std::function<void(const std::string&)>&& notification)
{
    return subscriptionManager_.subscribe<Firebolt::JSON::String>("Actions.onIntent", std::move(notification));
}

Result<void> ActionsImpl::unsubscribe(SubscriptionId id)
{
    return subscriptionManager_.unsubscribe(id);
}

void ActionsImpl::unsubscribeAll()
{
    subscriptionManager_.unsubscribeAll();
}

IActions* IActions::create() {
    return new ActionsImpl(Firebolt::Helpers::GetHelperInstance());
}

} // namespace Firebolt::Actions
