// ============================================================================
// AUTO-GENERATED by fb-gen — DO NOT EDIT
// ============================================================================
#ifndef FIREBOLT_ACTIONS_IMPL_H
#define FIREBOLT_ACTIONS_IMPL_H

#include "firebolt/actions.h"
#include <firebolt/helpers.h>

namespace Firebolt::Actions {

class ActionsImpl : public IActions {
public:
    explicit ActionsImpl(Firebolt::Helpers::IHelper& helper);
    ActionsImpl(const ActionsImpl&) = delete;
    ActionsImpl& operator=(const ActionsImpl&) = delete;
    ~ActionsImpl() override = default;

    Result<std::string> intent() const override;

    Result<SubscriptionId> subscribeOnIntent(std::function<void(const std::string&)>&& notification) override;

    Result<void> unsubscribe(SubscriptionId id) override;
    void unsubscribeAll() override;

private:
    Firebolt::Helpers::IHelper& helper_;
    Firebolt::Helpers::SubscriptionManager subscriptionManager_;
};

} // namespace Firebolt::Actions

#endif // FIREBOLT_ACTIONS_IMPL_H
