/**
 * Copyright 2026 Comcast Cable Communications Management, LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
//
// ============================================================================
// AUTO-GENERATED by fb-gen — DO NOT EDIT
// ============================================================================
#include "firebolt_module_impl.h"
#include "json_types/firebolt_module.h"
#include <firebolt/client_version.h>
#include <firebolt/json_types.h>
#include <nlohmann/json.hpp>
#include <regex>

namespace Firebolt::FireboltModule {

FireboltImpl::FireboltImpl(Firebolt::Helpers::IHelper& helper)
    : helper_(helper)
    , subscriptionManager_(helper, this)
{}

Result<std::string> FireboltImpl::serverVersion() const {
    return helper_.get<Firebolt::JSON::String, std::string>("Firebolt.serverVersion");
}
Result<SubscriptionId> FireboltImpl::subscribeOnServerVersionChanged(std::function<void(const std::string&)>&& notification) {
    return subscriptionManager_.subscribe<Firebolt::JSON::String>("Firebolt.onServerVersionChanged", std::move(notification));
}

Result<std::string> FireboltImpl::clientVersion() const {
    return Result<std::string>(std::string(Firebolt::Version::ClientString));
}
Result<SubscriptionId> FireboltImpl::subscribeOnClientVersionChanged(std::function<void(const std::string&)>&& notification) {
    return subscriptionManager_.subscribe<Firebolt::JSON::String>("Firebolt.onClientVersionChanged", std::move(notification));
}

Result<void> FireboltImpl::unsubscribe(SubscriptionId id) {
    return subscriptionManager_.unsubscribe(id);
}

void FireboltImpl::unsubscribeAll() {
    subscriptionManager_.unsubscribeAll();
}

} // namespace Firebolt::FireboltModule
