/**
 * Copyright 2026 Comcast Cable Communications Management, LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
//
// ============================================================================
// AUTO-GENERATED by firebolt-sdk-gen v0.1.0 — DO NOT EDIT
// ============================================================================
#include "videooutput_impl.h"
#include "json_types/videooutput.h"
#include <firebolt/json_types.h>
#include <nlohmann/json.hpp>
#include <regex>

namespace Firebolt::Videooutput
{
VideooutputImpl::VideooutputImpl(Firebolt::Helpers::IHelper& helper)
    : helper_(helper),
      subscriptionManager_(helper, this)
{
}

Result<VideoOutputResolution> VideooutputImpl::resolution() const
{
    return helper_.get<JsonData::VideoOutputResolution, VideoOutputResolution>("Videooutput.resolution");
}
Result<SubscriptionId>
VideooutputImpl::subscribeOnResolutionChanged(std::function<void(const VideoOutputResolution&)>&& notification)
{
    return subscriptionManager_.subscribe<JsonData::VideoOutputResolution>("Videooutput.onResolutionChanged",
                                                                           std::move(notification));
}

Result<HdcpState> VideooutputImpl::hdcp() const
{
    return helper_.get<Firebolt::JSON::BasicType<HdcpState>, HdcpState>("Videooutput.hdcp");
}
Result<SubscriptionId> VideooutputImpl::subscribeOnHdcpChanged(std::function<void(const HdcpState&)>&& notification)
{
    return subscriptionManager_.subscribe<Firebolt::JSON::BasicType<HdcpState>>("Videooutput.onHdcpChanged",
                                                                                std::move(notification));
}

Result<CecStateValue> VideooutputImpl::cecState() const
{
    return helper_.get<Firebolt::JSON::BasicType<CecStateValue>, CecStateValue>("Videooutput.cecState");
}
Result<SubscriptionId> VideooutputImpl::subscribeOnCecStateChanged(std::function<void(const CecStateValue&)>&& notification)
{
    return subscriptionManager_.subscribe<Firebolt::JSON::BasicType<CecStateValue>>("Videooutput.onCecStateChanged",
                                                                                    std::move(notification));
}

Result<RefreshRateValue> VideooutputImpl::refreshRate() const
{
    return helper_.get<Firebolt::JSON::BasicType<RefreshRateValue>, RefreshRateValue>("Videooutput.refreshRate");
}
Result<SubscriptionId>
VideooutputImpl::subscribeOnRefreshRateChanged(std::function<void(const RefreshRateValue&)>&& notification)
{
    return subscriptionManager_
        .subscribe<Firebolt::JSON::BasicType<RefreshRateValue>>("Videooutput.onRefreshRateChanged",
                                                                std::move(notification));
}

Result<ColorDepthValue> VideooutputImpl::colorDepth() const
{
    return helper_.get<Firebolt::JSON::BasicType<ColorDepthValue>, ColorDepthValue>("Videooutput.colorDepth");
}

Result<ColorFormatValue> VideooutputImpl::colorFormat() const
{
    return helper_.get<Firebolt::JSON::BasicType<ColorFormatValue>, ColorFormatValue>("Videooutput.colorFormat");
}

Result<OutputColorimetry> VideooutputImpl::colorimetry() const
{
    return helper_.get<Firebolt::JSON::BasicType<OutputColorimetry>, OutputColorimetry>("Videooutput.colorimetry");
}

Result<DynamicRangeValue> VideooutputImpl::dynamicRange() const
{
    return helper_.get<Firebolt::JSON::BasicType<DynamicRangeValue>, DynamicRangeValue>("Videooutput.dynamicRange");
}

Result<QuantizationRangeValue> VideooutputImpl::quantizationRange() const
{
    return helper_.get<Firebolt::JSON::BasicType<QuantizationRangeValue>, QuantizationRangeValue>(
        "Videooutput.quantizationRange");
}

Result<void> VideooutputImpl::unsubscribe(SubscriptionId id)
{
    return subscriptionManager_.unsubscribe(id);
}

void VideooutputImpl::unsubscribeAll()
{
    subscriptionManager_.unsubscribeAll();
}

} // namespace Firebolt::Videooutput
