/**
 * Copyright 2026 Comcast Cable Communications Management, LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
//
// ============================================================================
// AUTO-GENERATED by fb-gen — DO NOT EDIT
// ============================================================================
#ifndef FIREBOLT_ACTIONS_JSON_H
#define FIREBOLT_ACTIONS_JSON_H

#pragma once
#include "firebolt/actions.h"
#include <firebolt/json_types.h>
#include <nlohmann/json.hpp>
#include <stdexcept>

namespace Firebolt::Actions
{

namespace JsonData
{

// Deserialises the wire object {"intent":{"action":"...","context":{"source":"..."}},"intentId":N}
// into Firebolt::Actions::Intent. nlohmann stays hidden in this impl-layer header.
class JsonValue : public Firebolt::JSON::NL_Json_Basic<Intent>
{
public:
    void fromJson(const nlohmann::json& json) override
    {
        if (!checkRequiredFields(json, {"intent", "intentId"}) ||
            !json["intent"].is_object() ||
            !checkRequiredFields(json["intent"], {"action", "context"}) ||
            !json["intent"]["context"].is_object() ||
            !checkRequiredFields(json["intent"]["context"], {"source"}))
        {
            throw std::invalid_argument("Missing required fields in JSON");
        }
        value_.intent.action         = json["intent"]["action"].get<std::string>();
        value_.intent.context.source = json["intent"]["context"]["source"].get<std::string>();
        value_.intentId              = json["intentId"].get<uint32_t>();
    }
    Intent value() const override { return value_; }

private:
    Intent value_;
};

} // namespace JsonData

} // namespace Firebolt::Actions

#endif // FIREBOLT_ACTIONS_JSON_H
