/**
 * Copyright 2026 Comcast Cable Communications Management, LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
//
// ============================================================================
// AUTO-GENERATED by fb-gen — DO NOT EDIT
// ============================================================================
#ifndef FIREBOLT_ACTIONS_JSON_H
#define FIREBOLT_ACTIONS_JSON_H

#pragma once
#include "firebolt/actions.h"
#include <firebolt/json_types.h>
#include <nlohmann/json.hpp>
#include <type_traits>

namespace Firebolt::Actions
{

namespace JsonData
{

// Serialises any JSON value (object, string, …) to its compact JSON text
// representation. Used for Actions.intent / Actions.onIntent whose wire format
// is the object {"intent":"...","intentId":N} but whose public C++ API surface
// exposes the whole document as a std::string, per the Firebolt 9 spec.
class JsonString : public Firebolt::JSON::NL_Json_Basic<std::string>
{
public:
    void fromJson(const nlohmann::json& json) override { value_ = json.dump(); }
    std::string value() const override { return value_; }

private:
    std::string value_;
};

} // namespace JsonData

} // namespace Firebolt::Actions

#endif // FIREBOLT_ACTIONS_JSON_H
