// ============================================================================
// AUTO-GENERATED by fb-gen — DO NOT EDIT
// ============================================================================
#ifndef FIREBOLT_ACTIONS_JSON_H
#define FIREBOLT_ACTIONS_JSON_H

#pragma once
#include <type_traits>
#include <nlohmann/json.hpp>
#include <firebolt/json_types.h>
#include "firebolt/actions.h"

namespace Firebolt::Actions {

} // namespace Firebolt::Actions

#endif // FIREBOLT_ACTIONS_JSON_H
