/**
 * Copyright 2026 Comcast Cable Communications Management, LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
//
// ============================================================================
// AUTO-GENERATED by firebolt-sdk-gen v0.1.0 — DO NOT EDIT
// ============================================================================
#ifndef FIREBOLT_VIDEOOUTPUT_JSON_H
#define FIREBOLT_VIDEOOUTPUT_JSON_H

#include "firebolt/videooutput.h"
#include <firebolt/json_types.h>
#include <nlohmann/json.hpp>
#include <type_traits>

namespace Firebolt::VideoOutput
{

NLOHMANN_JSON_SERIALIZE_ENUM(CecStateValue, {
                                                {CecStateValue::Active, "ACTIVE"},
                                                {CecStateValue::Inactive, "INACTIVE"},
                                                {CecStateValue::Unsupported, "UNSUPPORTED"},
                                            })

NLOHMANN_JSON_SERIALIZE_ENUM(ColorDepthValue, {
                                                  {ColorDepthValue::D0, "D0"},
                                                  {ColorDepthValue::D10, "D10"},
                                                  {ColorDepthValue::D12, "D12"},
                                                  {ColorDepthValue::D8, "D8"},
                                              })

NLOHMANN_JSON_SERIALIZE_ENUM(ColorFormatValue, {
                                                   {ColorFormatValue::None, "NONE"},
                                                   {ColorFormatValue::Rgb444, "RGB444"},
                                                   {ColorFormatValue::Ycbcr420, "YCBCR420"},
                                                   {ColorFormatValue::Ycbcr422, "YCBCR422"},
                                                   {ColorFormatValue::Ycbcr444, "YCBCR444"},
                                               })

NLOHMANN_JSON_SERIALIZE_ENUM(DynamicRangeValue, {
                                                    {DynamicRangeValue::DolbyVision, "DOLBY_VISION"},
                                                    {DynamicRangeValue::Hdr10, "HDR10"},
                                                    {DynamicRangeValue::Hdr10plus, "HDR10PLUS"},
                                                    {DynamicRangeValue::Hlg, "HLG"},
                                                    {DynamicRangeValue::None, "NONE"},
                                                    {DynamicRangeValue::Sdr, "SDR"},
                                                })

NLOHMANN_JSON_SERIALIZE_ENUM(HdcpState, {
                                            {HdcpState::Direct, "DIRECT"},
                                            {HdcpState::Hdcp14, "HDCP14"},
                                            {HdcpState::Hdcp22, "HDCP22"},
                                            {HdcpState::None, "NONE"},
                                        })

NLOHMANN_JSON_SERIALIZE_ENUM(OutputColorimetry, {
                                                    {OutputColorimetry::Bt2020rgb, "BT2020RGB"},
                                                    {OutputColorimetry::Bt2020ycc, "BT2020YCC"},
                                                    {OutputColorimetry::Bt709, "BT709"},
                                                    {OutputColorimetry::None, "NONE"},
                                                    {OutputColorimetry::Oprgb, "OPRGB"},
                                                })

NLOHMANN_JSON_SERIALIZE_ENUM(QuantizationRangeValue, {
                                                         {QuantizationRangeValue::Full, "FULL"},
                                                         {QuantizationRangeValue::Limited, "LIMITED"},
                                                         {QuantizationRangeValue::None, "NONE"},
                                                     })

NLOHMANN_JSON_SERIALIZE_ENUM(RefreshRateValue, {
                                                   {RefreshRateValue::R0, "R0"},
                                                   {RefreshRateValue::R23976, "R23_976"},
                                                   {RefreshRateValue::R24, "R24"},
                                                   {RefreshRateValue::R25, "R25"},
                                                   {RefreshRateValue::R2997, "R29_97"},
                                                   {RefreshRateValue::R30, "R30"},
                                                   {RefreshRateValue::R50, "R50"},
                                                   {RefreshRateValue::R5994, "R59_94"},
                                                   {RefreshRateValue::R60, "R60"},
                                               })

namespace JsonData
{

inline const Firebolt::JSON::EnumType<::Firebolt::VideoOutput::CecStateValue> CecStateValueEnum({
    {"ACTIVE", ::Firebolt::VideoOutput::CecStateValue::Active},
    {"INACTIVE", ::Firebolt::VideoOutput::CecStateValue::Inactive},
    {"UNSUPPORTED", ::Firebolt::VideoOutput::CecStateValue::Unsupported},
});

inline const Firebolt::JSON::EnumType<::Firebolt::VideoOutput::ColorDepthValue> ColorDepthValueEnum({
    {"D0", ::Firebolt::VideoOutput::ColorDepthValue::D0},
    {"D10", ::Firebolt::VideoOutput::ColorDepthValue::D10},
    {"D12", ::Firebolt::VideoOutput::ColorDepthValue::D12},
    {"D8", ::Firebolt::VideoOutput::ColorDepthValue::D8},
});

inline const Firebolt::JSON::EnumType<::Firebolt::VideoOutput::ColorFormatValue> ColorFormatValueEnum({
    {"NONE", ::Firebolt::VideoOutput::ColorFormatValue::None},
    {"RGB444", ::Firebolt::VideoOutput::ColorFormatValue::Rgb444},
    {"YCBCR420", ::Firebolt::VideoOutput::ColorFormatValue::Ycbcr420},
    {"YCBCR422", ::Firebolt::VideoOutput::ColorFormatValue::Ycbcr422},
    {"YCBCR444", ::Firebolt::VideoOutput::ColorFormatValue::Ycbcr444},
});

inline const Firebolt::JSON::EnumType<::Firebolt::VideoOutput::DynamicRangeValue> DynamicRangeValueEnum({
    {"DOLBY_VISION", ::Firebolt::VideoOutput::DynamicRangeValue::DolbyVision},
    {"HDR10", ::Firebolt::VideoOutput::DynamicRangeValue::Hdr10},
    {"HDR10PLUS", ::Firebolt::VideoOutput::DynamicRangeValue::Hdr10plus},
    {"HLG", ::Firebolt::VideoOutput::DynamicRangeValue::Hlg},
    {"NONE", ::Firebolt::VideoOutput::DynamicRangeValue::None},
    {"SDR", ::Firebolt::VideoOutput::DynamicRangeValue::Sdr},
});

inline const Firebolt::JSON::EnumType<::Firebolt::VideoOutput::HdcpState> HdcpStateEnum({
    {"DIRECT", ::Firebolt::VideoOutput::HdcpState::Direct},
    {"HDCP14", ::Firebolt::VideoOutput::HdcpState::Hdcp14},
    {"HDCP22", ::Firebolt::VideoOutput::HdcpState::Hdcp22},
    {"NONE", ::Firebolt::VideoOutput::HdcpState::None},
});

inline const Firebolt::JSON::EnumType<::Firebolt::VideoOutput::OutputColorimetry> OutputColorimetryEnum({
    {"BT2020RGB", ::Firebolt::VideoOutput::OutputColorimetry::Bt2020rgb},
    {"BT2020YCC", ::Firebolt::VideoOutput::OutputColorimetry::Bt2020ycc},
    {"BT709", ::Firebolt::VideoOutput::OutputColorimetry::Bt709},
    {"NONE", ::Firebolt::VideoOutput::OutputColorimetry::None},
    {"OPRGB", ::Firebolt::VideoOutput::OutputColorimetry::Oprgb},
});

inline const Firebolt::JSON::EnumType<::Firebolt::VideoOutput::QuantizationRangeValue> QuantizationRangeValueEnum({
    {"FULL", ::Firebolt::VideoOutput::QuantizationRangeValue::Full},
    {"LIMITED", ::Firebolt::VideoOutput::QuantizationRangeValue::Limited},
    {"NONE", ::Firebolt::VideoOutput::QuantizationRangeValue::None},
});

inline const Firebolt::JSON::EnumType<::Firebolt::VideoOutput::RefreshRateValue> RefreshRateValueEnum({
    {"R0", ::Firebolt::VideoOutput::RefreshRateValue::R0},
    {"R23_976", ::Firebolt::VideoOutput::RefreshRateValue::R23976},
    {"R24", ::Firebolt::VideoOutput::RefreshRateValue::R24},
    {"R25", ::Firebolt::VideoOutput::RefreshRateValue::R25},
    {"R29_97", ::Firebolt::VideoOutput::RefreshRateValue::R2997},
    {"R30", ::Firebolt::VideoOutput::RefreshRateValue::R30},
    {"R50", ::Firebolt::VideoOutput::RefreshRateValue::R50},
    {"R59_94", ::Firebolt::VideoOutput::RefreshRateValue::R5994},
    {"R60", ::Firebolt::VideoOutput::RefreshRateValue::R60},
});

class VideoOutputResolution : public Firebolt::JSON::NL_Json_Basic<::Firebolt::VideoOutput::VideoOutputResolution>
{
public:
    void fromJson(const nlohmann::json& json) override
    {
        if (!checkRequiredFields(json, {"height", "width"}))
        {
            throw std::invalid_argument("Missing required fields in JSON");
        }
        height_ = json["height"].get<uint32_t>();
        width_ = json["width"].get<uint32_t>();
    }
    [[nodiscard]] ::Firebolt::VideoOutput::VideoOutputResolution value() const override
    {
        return ::Firebolt::VideoOutput::VideoOutputResolution{height_, width_};
    }

private:
    uint32_t height_{};
    uint32_t width_{};
};

} // namespace JsonData

inline void to_json(nlohmann::json& j, const VideoOutputResolution& v)
{
    j = nlohmann::json::object();
    j["height"] = v.height;
    j["width"] = v.width;
}

} // namespace Firebolt::VideoOutput

#endif // FIREBOLT_VIDEOOUTPUT_JSON_H
